{
 "title": "Ingress",
 "tags": [ "emojify" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests / s",
   "type": "singlestat",
   "description": "Number of inbound requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"service:emojify-api|service:emojify-website\",label_app=\"emojify-ingress\", envoy_response_code_class=~\"2|4\"}[60s]))"
    }
   ]
  },
  {
   "title": "Errors / s",
   "type": "singlestat",
   "description": "Number of outbound errors per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"service:emojify-api|service:emojify-website\",label_app=\"emojify-ingress\", envoy_response_code_class=\"5\"}[60s]))"
    }
   ]
  },
  {
   "title": "Pod CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name=~\"emojify-ingress-.*\",name=~\"^k8s_.*\"}[1m])) by(container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Pod Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",name=~\"^k8s_.*\",pod_name=~\"emojify-ingress-.*\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Envoy Listener Requests Inbound (Downstream)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"service:emojify-api|service:emojify-website\",label_app=\"emojify-ingress\"}[30s])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  { "title": "API Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "API Requests (count)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_cluster_name=\"service_emojify-api\"}[30s])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xx-"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_retry{envoy_cluster_name=\"service_emojify-api\"}[30s]))",
     "legendFormat": "retry"
    }
   ]
  },
  {
   "title": "API Requests (time)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_time{envoy_cluster_name=\"service_emojify-api\"} > 0) by (quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_time_sum{envoy_cluster_name=\"service_emojify-api\"}[30s]))/sum(rate(envoy_cluster_external_upstream_rq_time_count{envoy_cluster_name=\"service_emojify-api\"}[30s]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "API Timeouts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_timeout{envoy_cluster_name=\"service_emojify-api\"}[30s]))",
     "legendFormat": "global timeout"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_per_try_timeout{envoy_cluster_name=\"service_emojify-api\"}[30s]))",
     "legendFormat": "per try timeout "
    }
   ]
  },
  {
   "title": "API Outlier Ejections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active{envoy_cluster_name=\"service_emojify-api\"})",
     "legendFormat": "active"
    }
   ]
  },
  { "title": "Website Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Website Requests (count)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{label_app=\"emojify-ingress\",envoy_cluster_name=\"service_emojify-website\"}[30s])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}xxx"
    }
   ]
  },
  {
   "title": "Website Requests (time)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_time{envoy_cluster_name=\"service_emojify-website\"} > 0) by (quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_time_sum{envoy_cluster_name=\"service_emojify-website\"}[30s]))/sum(rate(envoy_cluster_external_upstream_rq_time_count{envoy_cluster_name=\"service_emojify-website\"}[30s]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Website Timeouts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_timeout{envoy_cluster_name=\"service_emojify-website\"}[30s]))",
     "legendFormat": "global timeout"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_per_try_timeout{envoy_cluster_name=\"service_emojify-website\"}[30s]))",
     "legendFormat": "per try timeout "
    }
   ]
  },
  {
   "title": "Website Outlier Ejections Active",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_outlier_detection_ejections_active{envoy_cluster_name=\"service_emojify-website\"}",
     "legendFormat": "{{label_app}}"
    }
   ]
  }
 ]
}